name: LicenseFinder CI
permissions: {}
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - "**"

jobs:
  test:
    name: Check dependencies license
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install pnpm
        run: corepack disable && npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install LicenseFinder
        run: gem install license_finder

      - name: Run LicenseFinder
        run: license_finder --decisions_file ./.github/dependency_decisions.yml
